on:
  workflow_dispatch:
    inputs:
      name:
        description: "Person to greet"
        required: true
        default: "bossm0n5t3r"
      home:
        description: "location"
        required: false
        default: "The Octoverse"
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"
